name: "Auto Close Stale Issues"
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 30
          days-before-close: 7
          stale-issue-message: "This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs."
          stale-pr-message: "This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs."
          close-issue-message: "This issue is being closed due to inactivity."
          close-pr-message: "This pull request is being closed due to inactivity."
          only-labels: ""
          exempt-issue-labels: "pinned, security"
          exempt-pr-labels: "work-in-progress"
          operations-per-run: 30
